version: "3.8"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-net

  api:
    build: .
    ports:
      - "8080:8080"
    networks:
      - api-net

networks:
  api-net:
    driver: bridge
