name: 🧪 list-vms
on:
  workflow_dispatch:
    inputs:
        env-file-path:
            description: 'Environment variables to login to Azure with OIDC'
            required: true
            default: './terraform/backends/azurerm-nonprd.env'

permissions:
 id-token: write
 contents: read

jobs:
  list-vms:
    #environment:
      #name: azurerm-auto
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add env variables
      run: cat ${{ inputs.env-file-path }} >>$GITHUB_ENV

    - name: Az CLI login
      uses: azure/login@v2
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

    - name: List VMs
      shell: pwsh
      run: |
        $tags = @("ApplicationID=1","ApplicationName=Azure Services","ApplicationOwner=azure","Provisioner=az cli")
        $jtags = $tags | ConvertTo-Json
        az group create -l westeurope -n myrg --tags $tags
        #az storage account update --name mysa --resource-group myrg
        #az storage container create -n tfstate --account-name mysa --auth-mode login