name: tasks
on:
  workflow_dispatch:

permissions:
 id-token: write
 contents: read

jobs:
  tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add env variables
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Job
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3

        python challenge-public-challenge/tests/run_tests.py


